import Head from "next/head";
import BoxLayout from "~/components/BoxLayout";
import { api } from "~/utils/api";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export default function Home() {
  const { mutate } = api.dataRouter.clearDatabase.useMutation({
    onSuccess: (dataObj) => {
      if (dataObj.success) {
        toast(`Database Data cleared :0`, { theme: "dark", autoClose: 5000 });
      }
    },
    onError: (e) => {
      console.log("the error ", e);
    },
  });

  const resetDatabaseHandler = async () => {
    await mutate();
  };
  return (
    <>
      <BoxLayout>
        <Head>
          <title>The Task App </title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className="mb-5 text-center text-3xl font-bold text-black">
          Welcome
        </h1>
        <h3 className="mb-1 text-center text-xl font-bold text-black">
          So , here are the end points via which you can navigate
        </h3>
        <ul className="text-center">
          <li>
            <a
              href="/signup-page"
              className="font-medium text-blue-600 hover:underline dark:text-blue-500"
            >
              Signup Page{" "}
            </a>
          </li>
          <li>
            <a
              href="/login-page"
              className="font-medium text-blue-600 hover:underline dark:text-blue-500"
            >
              Login Page{" "}
            </a>
          </li>
        </ul>
        <button
          className="mb-4 mt-3 w-full rounded-md bg-black px-4 py-2 tracking-widest text-white hover:bg-gray-900 focus:bg-gray-900 focus:outline-none"
          onClick={resetDatabaseHandler}
        >
          RESET DB
        </button>
      </BoxLayout>
      <ToastContainer />
    </>
  );
}
